# Generated by Django 6.0.4 on 2026-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsl', models.CharField(choices=[('atlas', 'Atlas (.atl)'), ('neptune', 'Neptune (.nep)'), ('hydra', 'Hydra (.hyd)'), ('chronos', 'Chronos (.chr)'), ('athena', 'Athena (.ath)')], max_length=20)),
                ('uploaded_file', models.FileField(upload_to='uploads/%Y%m%d/')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output_text', models.TextField(blank=True, default='')),
                ('error_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
