# Generated by Django 6.0.4 on 2026-05-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_runjob_cancel_requested_alter_runjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='input_manifest',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
